"""reset lozinke

Revision ID: 4e86660db904
Revises: 98eee650d232
Create Date: 2021-10-07 15:16:51.740510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e86660db904'
down_revision = '98eee650d232'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reset_lozinke',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('podnosilac', sa.String(length=15), nullable=False),
    sa.Column('kod', sa.String(length=5), nullable=False),
    sa.Column('nova_lozinka', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['podnosilac'], ['korisnik.korisnicko_ime'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reset_lozinke')
    # ### end Alembic commands ###
