"""change aranzman

Revision ID: a826ee6a4819
Revises: c9fdc2acbc60
Create Date: 2021-10-06 12:20:59.666663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a826ee6a4819'
down_revision = 'c9fdc2acbc60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aranzman', sa.Column('admin', sa.String(length=50), nullable=False))
    op.create_foreign_key(None, 'aranzman', 'korisnik', ['admin'], ['korisnicko_ime'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'aranzman', type_='foreignkey')
    op.drop_column('aranzman', 'admin')
    # ### end Alembic commands ###
