"""zahtev status

Revision ID: bd92357c58db
Revises: a826ee6a4819
Create Date: 2021-10-06 15:11:03.583942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd92357c58db'
down_revision = 'a826ee6a4819'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zahtev', sa.Column('status', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zahtev', 'status')
    # ### end Alembic commands ###
