"""Initial migration.

Revision ID: c9fdc2acbc60
Revises: 
Create Date: 2021-10-06 11:36:50.770522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9fdc2acbc60'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('korisnik',
    sa.Column('ime', sa.String(length=20), nullable=False),
    sa.Column('prezime', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('korisnicko_ime', sa.String(length=50), nullable=False),
    sa.Column('lozinka', sa.Text(), nullable=False),
    sa.Column('tip_naloga', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('korisnicko_ime'),
    sa.UniqueConstraint('email')
    )
    op.create_table('aranzman',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opis', sa.Text(), nullable=False),
    sa.Column('destinacija', sa.String(length=50), nullable=False),
    sa.Column('broj_mesta', sa.Integer(), nullable=False),
    sa.Column('cena', sa.Float(), nullable=False),
    sa.Column('pocetak', sa.DateTime(), nullable=False),
    sa.Column('kraj', sa.DateTime(), nullable=False),
    sa.Column('vodic', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['vodic'], ['korisnik.korisnicko_ime'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zahtev',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('podnosilac', sa.String(length=15), nullable=False),
    sa.Column('zeljeni_nalog', sa.String(length=15), nullable=False),
    sa.ForeignKeyConstraint(['podnosilac'], ['korisnik.korisnicko_ime'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rezervacija',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aranzman', sa.Integer(), nullable=False),
    sa.Column('korisnik', sa.String(length=50), nullable=False),
    sa.Column('broj_mesta', sa.Integer(), nullable=False),
    sa.Column('ukupna_cena', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['aranzman'], ['aranzman.id'], ),
    sa.ForeignKeyConstraint(['korisnik'], ['korisnik.korisnicko_ime'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rezervacija')
    op.drop_table('zahtev')
    op.drop_table('aranzman')
    op.drop_table('korisnik')
    # ### end Alembic commands ###
